# Generated by Django 4.2.3 on 2023-07-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identification',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
