# Generated by Django 4.2.3 on 2023-07-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_identification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='identification',
            new_name='identification_number',
        ),
    ]
